# Generated by Django 4.2.2 on 2023-12-06 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='action',
            name='action',
        ),
        migrations.RemoveField(
            model_name='action',
            name='date',
        ),
        migrations.RemoveField(
            model_name='action',
            name='name',
        ),
        migrations.RemoveField(
            model_name='action',
            name='type',
        ),
        migrations.AddField(
            model_name='action',
            name='msg',
            field=models.CharField(default='', max_length=300),
            preserve_default=False,
        ),
    ]
